name: MyappContainer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: nkatsacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t nkatsacr.azurecr.io/sampleapp:latest -f Dockerfile.Dockerfile
        docker push nkatsacr.azurecr.io/sampleapp:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'nkatswebcontainer'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'nkatsacr.azurecr.io/sampleapp:${{ github.sha }}'
