name: MyappContainer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Build and push image' 
      uses: azure/docker-login@v1
      with:
        login-server: nkatsacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t nkatsacr.azurecr.io/sampleapp:${{ github.sha }}
        docker push nkatsacr.azurecr.io/sampleapp:${{ github.sha }}     
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
   
    steps:
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nkatswebcontainer'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'nkatsacr.azurecr.io/sampleapp:${{ github.sha }}'
